version: "3"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    hostname: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
    - type: volume
      source: data
      target: /var/lib/postgresql/data

  #elastic:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    env_file: .env
    ports:
    - "8080:8080"
    depends_on:
      - postgres

volumes:
  data: