version: "3"

services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
    - type: bind
      source: data
      destination: /var/

  #elastic:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    env_file:
      - .env
    ports:
    - "8080:8080"

volumes:
  data: