version: "3"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    hostname: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
    - type: volume
      source: pgdata
      target: /var/lib/postgresql/data

  #elastic:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    env_file: .env
    ports:
    - "8080:8080"
    depends_on:
      - postgres
      - elasticsearch

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
    - "9200:9200"
    volumes:
    - esdata:/usr/share/elasticsearch/data

  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.10.2'
    ports:
    - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200


volumes:
  pgdata:
    driver: local
  esdata:
    driver: local